logging:
  level:
    org.ech.phr: DEBUG
    org.apache.zookeeper: trace

server:
  port: 8081
  contextPath: /phr

tomcat:
  ajp:
    port: 8009
    remoteauthentication: false
    enabled: true
 
hbase:
  zookeeper:
    quorum: 127.0.0.1:2181